services:
  dynamodb-money-manager:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-money-manager
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root

  dynamodb-money-manager-admin:
    container_name: dynamodb-money-manager-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      DYNAMO_ENDPOINT: ${DYNAMO_ENDPOINT}
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-money-manager
